name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.USERNAME }}
        DOCKER_PASS: ${{ secrets.PASSWORD }}
      run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

    - name: Build and push Docker image
      run: |
        docker build -t motormind .
        docker push motormind
