name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to docker hub
      run: docker login -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}
      
    - name: Build the Docker image
      run: docker build -t motormind .

    - name: Tagging the image
      run: docker tag mortormind muasyadennis/motormind:latest

    - name: push image to docker hub
      run: docker push muasyadennis/motormind:latest

